[tool.poetry]
name = "webscrapping"
version = "0.1.0"
description = "Projeto de WebScrapping utilizando modelo de LLM local"
authors = ["marcovins <marcosbelods@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
